### ISSUE TITLE
Non redirect version

### ISSUE THREAD

**Issue by mikedoubintchik** [dalpras/omnipay-constriv#1]
Thank you for creating this repo. I'm looking to implement the constriv non-redirect gateway.

Do you have any plans in creating that? It would be very helpful!

**Comment by dalpras** [comment]
Version 2.0 is already not redirecting. It works with omnipay 3.




Documentation perhaps lacks of this note.




Bye




Stefano Dal Prà







On Thu, Nov 29, 2018 at 8:33 AM +0100, "Mike Doubintchik" <notifications@github.com> wrote:












Thank you for creating this repo. I'm looking to implement the constriv non-redirect gateway.


Do you have any plans in creating that? It would be very helpful!

**Comment by allurewebsolutions** [comment]
It would be super helpful if you could update the documentation or provide an example implementation. I'm getting stuck on the usage. Thank you in advance!!
